name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Verify build
        run: go build ./...

      - name: Run vet
        run: go vet ./...

      - name: Run tests
        run: go test -race -cover ./...

      - name: Compute version
        id: vars
        shell: bash
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "version=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
          else
            echo "version=dev-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
          fi

      - name: Build with version stamp
        run: |
          go build -ldflags "-X github.com/scarf-sh/scarf-go/scarf.sdkVersion=${{ steps.vars.outputs.version }}" ./...
